# server
server:
  port: 9090


# Spring Boot 
spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name:
      selloum-root

# Redis
  data:
    redis:
      host: ${REDIS_HOST} 
      port: ${REDIS_PORT}
      blacklist-key: ${REDIS_BLACKLIST_KEY}

# Main DataBase - MySQL
  datasource:                               
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      default_batch_fetch_size: 100

# Email Verifying
  mail:
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL_USERNAME}
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          writetimeout: 5000
          timeout: 5000
    auth-code-expiration-millis: 1800000


# Email Property
mail:
  from:
    email: ${MAIL_FROM_EMAIL}
    name: Example Service
  support:
  email: support@example.com
  prefix: 
    register: ${EMAIL_REDIS_PREFIX}
    reset-code: ${EMAIL_REDIS_PREFIX}
    reset-verify: ${EMAIL_REDIS_PREFIX}

springdoc:
  swagger-ui:
    groups-order: DESC
    operations-sorter: method
    display-request-duration: true
  show-actuator: true


jwt:
  header:
    access: ${JWT_TOKEN_ACCESS_HEADER}
    refresh: ${JWT_TOKEN_REFRESH_HEADER}
  secret-key: ${JWT_TOKEN_SECRET}
  prefix: ${JWT_TOKEN_PREFIX}
  issuer: ${JWT_TOKEN_ISSUER}
  expiration: 
    access: ${JWT_TOKEN_ACCESS_EXPIRATION}
    refresh: ${JWT_TOKEN_REFRESH_EXPIRATION}
  

logging:
  level:
    org.springframework.security.web.FilterChainProxy: TRACE




